### ISSUE TITLE
Data counter from left side to right side

### ISSUE THREAD

**Issue by tarun98678** [Simplicity-Team/WooBoxForMIUI#116]
Can you add modification to shift data counter from left side to right side.
![IMG_20220327_163255](https://user-images.githubusercontent.com/62491146/160278489-4392205e-dee8-4f35-9cc4-6982f0946aa1.jpg)

**Comment by backzaa** [comment]
![Screenshot_2022-03-28-06-28-55-366-edit_com lt2333 simplicitytools](https://user-images.githubusercontent.com/36920655/160305839-bc1d5ecf-2b47-4597-85b5-a4ad4aec53cb.jpg)

**Comment by tarun98678** [comment]
![Screenshot_2022-03-28-10-31-38-638_com lt2333 simplicitytools](https://user-images.githubusercontent.com/62491146/160329629-7a330fee-0bbf-49aa-a21d-16d9f295c604.png)

**Comment by tarun98678** [comment]
See its not working when i set it to right. With this left right option just the dual row icon changes its position.

**Comment by tarun98678** [comment]
![IMG_20220328_103622](https://user-images.githubusercontent.com/62491146/160329996-d8a8ce85-0531-4bf9-aa5d-d8a00b966b8a.jpg)
![IMG_20220328_103640](https://user-images.githubusercontent.com/62491146/160329983-338878d2-456e-4d7d-a248-65794bdc4a6c.jpg)

**Comment by backzaa** [comment]
When change it. Do you restart system ui?
![IMG_20220331_204217](https://user-images.githubusercontent.com/36920655/161069541-1f61241d-525a-4be7-a106-da95ea26206b.jpg)
![IMG_20220331_204248](https://user-images.githubusercontent.com/36920655/161069559-44f17b07-6a61-41da-8d7b-4820f1d6b5a6.jpg)

**Comment by tarun98678** [comment]
Yes i did.

**Comment by eritpchy** [comment]
![10201649170006_ pic](https://user-images.githubusercontent.com/8630635/161781120-9841a315-6698-4496-b7a8-5dec2308a490.jpg)
Same problem on K50 MIUI 13.0.7.0 stable

**Comment by eritpchy** [comment]
![Screenshot_2022-04-05-23-51-24-610_com.github.android.jpg](https://user-images.githubusercontent.com/8630635/161794672-76c56c28-42d6-4f96-aa33-6cbc2456f337.jpg)
目前发现装了https://github.com/Yejia995/K50FullScreen/releases这个模块他自己就到右边去了

**Comment by tarun98678** [comment]
> ![Screenshot_2022-04-05-23-51-24-610_com.github.android.jpg](https://user-images.githubusercontent.com/8630635/161794672-76c56c28-42d6-4f96-aa33-6cbc2456f337.jpg) https://github.com/Yejia995/K50FullScreen/releases 目前发现装了这个模块他自己就到右边去了

Mine is k40
