### ISSUE TITLE
[BUG] Mi 11 Clock

### ISSUE THREAD

**Issue by senkrad76** [Simplicity-Team/WooBoxForMIUI#151]
**描述一下BUG情况**
清晰明了的描述BUG的情况

**如何复现**
复现的步骤
1. 去  '...'
2. 点击  '....'
3. 滚动到  '....'
4. 问题出现

**截图**
如果可以，请添加截图以帮助解释您的问
![IMG_20220418_121948](https://user-images.githubusercontent.com/9276272/163863517-dae14c59-723a-4990-8f75-daf51665c16e.jpg)
题。

**手机信息：**
 - 设备型号：
 - MIUI版本：
 - Android版本：
![Screenshot_2022-04-18-12-18-08-097_com android chrome](https://user-images.githubusercontent.com/9276272/163863274-030fe6fb-0dc9-4458-90e1-e5c8a032b6dd.jpg)

**附加信息**
在此处添加有关此问题的任何其他内容。

On the Mi 11 when setting clock to center, it seems to keep the offset for the notch.

**Comment by LittleTurtle2333** [comment]
Open compatibility mode

**Comment by senkrad76** [comment]
Sorry I missed that, thank you!
