### ISSUE TITLE
[Feature] 希望在MIUI13 A12上增加通知模糊

### ISSUE THREAD

**Issue by nowcube** [Simplicity-Team/WooBoxForMIUI#153]
MIUI12.5的通知模糊很好看，但是MIUI13上却被替换为半透明，通知模糊真的好好看呀！真希望能在MIUI13上也看见它

**Comment by nowcube** [comment]
找到了一份文档 A12的
https://source.android.com/devices/tech/display/window-blurs

**Comment by LittleTurtle2333** [comment]
无计划
