### ISSUE TITLE
Theme

### ISSUE THREAD

**Issue by Muchoshka** [Simplicity-Team/WooBoxForMIUI#156]
The purple text is unreadable. A lighter dark mode or light mode would be a good setting to add as well.

![Screenshot_2022-04-29-10-59-55-679_com.lt2333.simplicitytools.jpg](https://user-images.githubusercontent.com/103844055/165914942-102c801f-bc17-423a-b56d-8fd286e7ffb1.jpg)

**Comment by LittleTurtle2333** [comment]
fixed
