### ISSUE TITLE
[BUG] disable digest not working

### ISSUE THREAD

**Issue by Mahantor** [Simplicity-Team/WooBoxForMIUI#158]
**描述一下BUG情况**
清晰明了的描述BUG的情况
Disable degist verify and other options not working
I rebooted several times and turned the settings on and off, but I still get the digest warning when installing the app.
![Screenshot_2022-04-29-15-07-50-116-edit_com.lt2333.simplicitytools.jpg](https://user-images.githubusercontent.com/91434001/165929932-e639c2ab-3ead-4ef0-94e3-f7323a33d7e8.jpg)

**如何复现**
复现的步骤
1. 去  '...'
2. 点击  '....'
3. 滚动到  '....'
4. 问题出现

**截图**
如果可以，请添加截图以帮助解释您的问题。

**手机信息：**
 - 设备型号：xiaomi redmi note 9 pro
 - MIUI版本：13
 - Android版本：12

**附加信息**
在此处添加有关此问题的任何其他内容。
I'm currently using the lucky patcher patch and it works fine
I hope this problem is solved in the next version

**Comment by LittleTurtle2333** [comment]
fixed
