### ISSUE TITLE
[Feature] 隐藏图标增加隐藏NFC图标选项

### ISSUE THREAD

**Issue by bling-yshs** [Simplicity-Team/WooBoxForMIUI#162]
最新的MIUI内测版添加了这个图标，让本不富余的状态栏空位雪上加霜....请求添加一个隐藏此图标的选项
![Screenshot_2022-05-10-17-57-22-424_com tencent mobileqq png](https://user-images.githubusercontent.com/41812674/167603129-a3156efc-50c1-41aa-9b7b-362f02913000.png)

**Comment by LittleTurtle2333** [comment]
#163
