### ISSUE TITLE
[BUG]状态栏网速双排的时候，网速显示不正确

### ISSUE THREAD

**Issue by lvzhenbo** [Simplicity-Team/WooBoxForMIUI#170]
**描述一下BUG情况**
状态栏网速双排的时候，网速显示不正确(似乎单位是Mbps)

**如何复现**
复现的步骤
1. 打开双排网络速度
2. 随意下载文件使用网络

**截图**
![Screenshot_2022-05-31-13-26-42-504_com.android.vending.jpg](https://user-images.githubusercontent.com/32427677/171099186-a5fd9049-5f0c-4c66-b5cb-814e0d0edf58.jpg)

**手机信息：**
 - 设备型号：MIX4
 - MIUI版本：13.0.6
 - Android版本：12

**附加信息**
如果是单位问题，最好是能够自己选择单位

**Comment by zzzsw7** [comment]
你开着梯子肯定不对啊...

**Comment by lvzhenbo** [comment]
哦，原来这样的吗，那没事了
