### ISSUE TITLE
[BUG] 移除屏幕截图限制后截图App闪退

### ISSUE THREAD

**Issue by yeahjack** [Simplicity-Team/WooBoxForMIUI#176]
**描述一下BUG情况**
升级MIUI开发版22.6.15后，小米10开启移除屏幕截图限制后截图App闪退。

**如何复现**
复现的步骤
1. 截图
2. 编辑截图
3. 拖动剪辑框
4. 截图App闪退

**截图**
如果可以，请添加截图以帮助解释您的问题。

**手机信息：**
 - 设备型号：小米10
 - MIUI版本：开发版22.6.15
 - Android版本：12

**附加信息**
在此处添加有关此问题的任何其他内容。

**Comment by Liangzaigrape** [comment]
11u最新内测也有这问题

**Comment by ljcbaby** [comment]
Redmi Note 9 Pro 开发内测，同复现

**Comment by StandGreat** [comment]
k40开发版内测也有 有几个版本了 现在22.6.24
