### ISSUE TITLE
蓝牙图标无法隐藏

### ISSUE THREAD

**Issue by czmweb** [Simplicity-Team/WooBoxForMIUI#181]
蓝牙图标无法隐藏，网速不能秒刷新，网速分隔符无法隐藏，网速单位无法隐藏，通知中心无法显示天气

**手机信息：**
 - 设备型号：Redmi K40
 - MIUI版本：MIUI 13.0.6.0 稳定版
 - Android版本：Android 12

Lsposed日志:https://wws.lanzouy.com/iTbbl07ab56f

**Comment by LittleTurtle2333** [comment]
等待MIUI官方更新上游代码
