### ISSUE TITLE
[BUG]状态栏布局在切换到横屏布局后发生错位

### ISSUE THREAD

**Issue by kingofotaku** [Simplicity-Team/WooBoxForMIUI#185]
**描述一下BUG情况**
清晰明了的描述BUG的情况
状态栏布局在切换到横屏布局后发生错位
**如何复现**
复现的步骤
1. 在模块中修改过状态栏左右边距的情况下，打开横屏app后切回竖屏即出现。

**截图**
如果可以，请添加截图以帮助解释您的问题。
正常情况：（左上角的空缺是前摄）
![Screenshot_2022-08-17-00-58-48-643_com miui home](https://user-images.githubusercontent.com/12953574/184937359-275372f9-833a-4d91-af02-2427b2fd4936.jpg)
错位后：
![Screenshot_2022-08-17-00-57-11-542_com miui home](https://user-images.githubusercontent.com/12953574/184937470-e7681c01-bbfc-48be-b77d-635d41772f01.jpg)

**手机信息：**
 - 设备型号：红米k30s
 - MIUI版本：MIUI 13 by xiaomi.eu weekly 22.8.3
 - Android版本：12

**附加信息**
在此处添加有关此问题的任何其他内容。

**Comment by Orionx-Lampros** [comment]
我也是这样

**Comment by kingofotaku** [comment]
> 到时候会重构这个功能

更新到1.7.4后发现只有选择时钟居中+图标在右时，横屏后才不会错位，其他两种模式下问题依旧。

**Comment by LittleTurtle2333** [comment]
试下 https://github.com/Simplicity-Team/WooBoxForMIUI/suites/11070518856/artifacts/563138526 登录后才能下载

**Comment by kingofotaku** [comment]
仍未改善获取Outlook for Android发件人: ***@***.*** ***@***.***> 代表 乌堆小透明 ***@***.***>发送时间: 2023年2月19日星期日 17:14收件人: WooBoxForMIUI ***@***.***>抄送: 754318010 ***@***.***>; author ***@***.***>主题: Re: [Simplicity-Team/WooBoxForMIUI] [BUG]状态栏布局在切换到横屏布局后发生错位 (Issue #185)

试下 https://github.com/Simplicity-Team/WooBoxForMIUI/suites/11070518856/artifacts/563138526 登录后才能下载

**Comment by kingofotaku** [comment]
仍未改善获取Outlook for Android发件人: ***@***.*** ***@***.***> 代表 乌堆小透明 ***@***.***>发送时间: 2023年2月19日星期日 17:14收件人: WooBoxForMIUI ***@***.***>抄送: 754318010 ***@***.***>; author ***@***.***>主题: Re: [Simplicity-Team/WooBoxForMIUI] [BUG]状态栏布局在切换到横屏布局后发生错位 (Issue #185)试下 https://github.com/Simplicity-Team/WooBoxForMIUI/suites/11070518856/artifacts/563138526 登录后才能下载—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by kingofotaku** [comment]
> 试下 https://github.com/Simplicity-Team/WooBoxForMIUI/suites/11070518856/artifacts/563138526 登录后才能下载

已尝试，仍未改善。

**Comment by LittleTurtle2333** [comment]
重启作用域了吗，或者你试试把左右边距都固定

**Comment by LittleTurtle2333** [comment]
不对啊，你这是Android12，我现在只管Android13了。不过这块的代码是一样的。我把a12同步一下

**Comment by LittleTurtle2333** [comment]
https://github.com/Simplicity-Team/WooBoxForMIUI/actions/runs/4216821308 试下这个版本

**Comment by kingofotaku** [comment]
> https://github.com/Simplicity-Team/WooBoxForMIUI/actions/runs/4216821308 试下这个版本

实测基本修复 唯一的问题是将左边距设置自动后计算出的距离会让摄像头刚好吞掉第一个通知图标（我k30s是左上摄像头）不过只要固定数值就没有问题了 横屏错位似乎也彻底解决了 感谢大佬
