### ISSUE TITLE
开启通知中心总开关直接升天。如图所示，真的是顶到天上了。[BUG]

### ISSUE THREAD

**Issue by cancundeyingzi** [Simplicity-Team/WooBoxForMIUI#188]
**描述一下BUG情况**
清晰明了的描述BUG的情况

**如何复现**
复现的步骤
1. 去  '...'
2. 点击  '....'
3. 滚动到  '....'
4. 问题出现

**截图**
![Screenshot_2022-08-21-16-07-56-632_com lt2333 simplicitytools](https://user-images.githubusercontent.com/73635883/185782153-18be9b97-5d3d-4bc5-add5-c7aaefe47c68.jpg)

如果可以，请添加截图以帮助解释您的问题。

**手机信息：**
 - 设备型号：小米mix4
 - MIUI版本：8.19你发的官改
 - Android版本：12

**附加信息**
在此处添加有关此问题的任何其他内容。

**Comment by cancundeyingzi** [comment]
经过反复测试，就是这个开关的问题。关了自动恢复，开了又变成截图这样子。

**Comment by LittleTurtle2333** [comment]
没有MIX4，无法修复，不同机型显示效果不一致

**Comment by LittleTurtle2333** [comment]
但你可以尝试自行修复后提交Pr
