### ISSUE TITLE
建议添加“无设备连接蓝牙时，隐藏蓝牙图标”

### ISSUE THREAD

**Issue by HankAviator** [Simplicity-Team/WooBoxForMIUI#191]
如标题所述，仅在连接了蓝牙设备时显示蓝牙图标，不知道好不好实现，或者如果支持第三方修改也可以(tasker)

**Comment by HankAviator** [comment]
已成为22.9.7的默认行为

**Comment by HankAviator** [comment]
后续MIUI版本回退了上面的更改

**Comment by LittleTurtle2333** [comment]
现在官方又有了

**Comment by HankAviator** [comment]
你好，我使用的小米11 Pro（mars/star）在MIUI14（xiaomi.eu，14.0.23.2.21）上没有隐藏未连接蓝牙的设置，也不会自动隐藏蓝牙图标
