### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Orionx-Lampros** [Simplicity-Team/WooBoxForMIUI#197]
**描述一下BUG情况**
横屏或者长时间息屏后，切换回竖屏模式，状态栏错位。整体向右移动（时钟居中，兼容左右挖孔模式）

**如何复现**
复现的步骤
1. 进入任意横屏场景
2. 切换回竖屏
3. 问题出现

**截图**
如果可以，请添加截图以帮助解释您的问题。
![Screenshot_2022-10-11-10-46-53-422_com lt2333 simplicitytools](https://user-images.githubusercontent.com/103523584/194986242-117ba176-302e-4272-bfb0-70fc89d9ff27.jpg)

**手机信息：**
 - 设备型号：小米 11 Pro
 - MIUI版本：MIUI 13 稳定版 13.0.13
 - Android版本：12

**附加信息**
在此处添加有关此问题的任何其他内容。

**Comment by LittleTurtle2333** [comment]
Android12早期版本中才会出现这类问题
