### ISSUE TITLE
[Feature]隐藏刘海，状态栏在刘海外&屏幕直角

### ISSUE THREAD

**Issue by kagaricyan** [Simplicity-Team/WooBoxForMIUI#199]
1：以前miui有这个选项，现在没有了
2：我想要让屏幕4个角变为直角，但是MIUI在4个角加了遮罩，有没有办法去掉呢？

原因：我想配合自定义分辨率使用，调小高度。这样显示区域完整 但是圆角看不惯。显示区域到摄像头下面了，状态栏中间还有个黑点。
因为OLED黑色不发光，我也不觉得难看

**Comment by LittleTurtle2333** [comment]
这个用Magisk模块实现，会更加容易。而且也不会有什么大改动。这些东西在/system/product/overlay/DevicesOverlay.apk/res下面
