### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by HackerNucleon** [Simplicity-Team/WooBoxForMIUI#200]
**描述一下BUG情况**
一旦关了“自动设置时间”，状态栏的时钟显秒就会一直为00，再开也一样

**如何复现**
复现的步骤
1.“设置”里找到“更多设置”，然后找到“日期和时间”
2.关闭“自动设置时间”，然后随便在下面设置时间
3.（其实2的时候就已经出现问题了）再重新打开“自动设置时间”

**截图**
![Uploading Screenshot_2022-10-16-14-13-11-078_com.lt2333.simplicitytools.jpg…]()
![Screenshot_2022-10-16-14-12-57-304_com lemurbrowser exts](https://user-images.githubusercontent.com/68340847/196021281-0acbb9fe-a1ce-40b1-be22-ac538b71db5b.jpg)

**手机信息：**
 - 设备型号：Redmi k30
 - MIUI版本：13.0.6.0
 - Android版本：12

**附加信息**
其实有可能重启就能解决问题，但我还是希望作者可以修一修，不用重启就可以恢复正常(

**Comment by LittleTurtle2333** [comment]
无法复现
