### ISSUE TITLE
[BUG]移除OTA验证失败

### ISSUE THREAD

**Issue by 1457384613gh** [Simplicity-Team/WooBoxForMIUI#201]
**描述一下BUG情况**
清晰明了的描述BUG的情况
如图所示，更加直观。
**如何复现**
复现的步骤
1. 去  'WooBox'
2. 点击  '图一'
3. 滚动到  '重启后刷稳定版内测包'
4. 问题出现

**截图**
如果可以，请添加截图以帮助解释您的问题。
![-67adccb7efa4c091.jpg](https://user-images.githubusercontent.com/69227436/197306599-104867a7-29e4-4d34-ace6-19c1bfdf4cd5.jpg)
![77f749464ebbf193.jpg](https://user-images.githubusercontent.com/69227436/197306601-324c1cc8-a933-4ad1-b19f-1d7b2b369a48.jpg)
**手机信息：**
 - 设备型号：choppin
 - MIUI版本：13.0.8.0
 - Android版本：12

**附加信息**
在此处添加有关此问题的任何其他内容。

**Comment by maboloshi** [comment]
可尝试面具模块 [ianchb / MIUI-Flash-Freely](https://github.com/ianchb/MIUI-Flash-Freely) 我的 k50 已偷渡到 MIUI14

**Comment by 1457384613gh** [comment]
> 可尝试面具模块 [ianchb / MIUI-Flash-Freely](https://github.com/ianchb/MIUI-Flash-Freely) 我的 k50 已偷渡到 MIUI14

虽然还没试，但是多谢推荐。
