### ISSUE TITLE
[BUG] MIUI14状态栏兼容模式失效

### ISSUE THREAD

**Issue by dogdie233** [Simplicity-Team/WooBoxForMIUI#208]
**描述一下BUG情况**
清晰明了的描述BUG的情况

**如何复现**
如下图设置

**截图**
这是状态栏的网速位置
![这是状态栏的网速位置](https://user-images.githubusercontent.com/42267840/208227758-de4ba1ae-4d69-49d5-8098-b9c926ec1dfa.jpg)
这是控制中心的网速位置（在miui13下是这个位置）
![正确的位置](https://user-images.githubusercontent.com/42267840/208227778-538cf0e5-1991-451f-9db2-471baaf2fb91.jpg)

**手机信息：**
 - 设备型号：redmi k50
 - MIUI版本：MIUI 14.0.22.12.5 Simplicity ROM
 - Android版本：13

**附加信息**

**Comment by dogdie233** [comment]
还有`自定义移动类型文本`也失效了

**Comment by LittleTurtle2333** [comment]
K50是居中挖孔，所以默认网速就是在左边的。

**Comment by LittleTurtle2333** [comment]
控制中心的状态栏，因为在挖孔下面，所以默认也是在挖孔右边的

**Comment by LittleTurtle2333** [comment]
你要反应的状态栏兼容模式失效了，那个功能可以把所有的异型屏幕都变成完整屏的显示方式

**Comment by dogdie233** [comment]
> 你要反应的状态栏兼容模式失效了，那个功能可以把所有的异型屏幕都变成完整屏的显示方式

功能开太多了，一更新失效了好多没分出来，抱歉抱歉😭
