### ISSUE TITLE
[BUG] 修复部分界面无法截图的方法

### ISSUE THREAD

**Issue by hosizoraru** [Simplicity-Team/WooBoxForMIUI#219]
findMethod("com.android.server.wm.WindowState") {
    name == "isSecureLocked"
}.hookReturnConstant(false)
findMethod("com.android.server.wm.WindowManagerService") {
    name == "isSecureLocked"
}.hookReturnConstant(false)
即使Hook这两个方法返回false，在部分界面依旧无法截图，比如私密相册。

https://github.com/LSPosed/DisableFlagSecure/blob/main/app/src/main/java/io/github/lsposed/disableflagsecure/DisableFlagSecure.java
然后今天发现西大师更新了一下这个模块，修复了A13上的支持，测试了一下，发现他的模块能够允许在私密相册里面截图了，希望乌堆能合并一下。

测试是否有效的话，比较简单的办法就是进去相册的私密相册里面截图，成功了就是能够截图，失败了就是提示该应用不允许屏幕截图。

测试发现西大师对A13的支持对于 XiaomiMix4 A13 14.0.23.2.6 有效果

**Comment by LittleTurtle2333** [comment]
差评，fork不PR😂
